// File generated by `flutterfire_cli`.
// For usage information, run: `flutterfire --help`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/material.dart' show TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    if (identical(defaultTargetPlatform, TargetPlatform.macOS)) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for macos - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjH1pSjDjP-9K9nWLan6W2GnR-1NTHJPA',
    appId: '1:443939139404:android:bffb6aabc43ffb565769e9',
    messagingSenderId: '443939139404',
    projectId: 'impactknowledge-ab14f',
    databaseURL: 'https://impactknowledge-ab14f.firebaseio.com',
    storageBucket: 'impactknowledge-ab14f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // IMPORTANT: iOS configuration - fill in after creating Firebase project
    apiKey: 'YOUR_IOS_API_KEY_FROM_FIREBASE',
    appId: 'YOUR_IOS_APP_ID_FROM_FIREBASE',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'https://YOUR_PROJECT_ID.firebaseio.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.impactknowledge.impactknowledgeApp',
  );
}

// Helper to get default target platform
const defaultTargetPlatform = TargetPlatform.android;
